__all__ = ["WINDOW_WIDTH", "WINDOW_HEIGHT", "ENEMY_SPAWN_TIMER"]

WINDOW_WIDTH = 1600
WINDOW_HEIGHT = 900

ENEMY_SPAWN_TIMER = 1

DEFAULT_SCREEN_MULTIPLIER = 2
PLAYER_KILL_MULTIPLIER = 15
ENEMY_HIT_MULTIPLIER = 10
